version: '3.8'

services:
  woyfitServer:
    build:
      context: .
    image: diverbriz/woyfit_server
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/woyfit
      - SPRING_DATASOURCE_USERNAME=vladimir
      - SPRING_DATASOURCE_PASSWORD=mrack2319
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "woyfit"
      POSTGRES_USER: "vladimir"
      POSTGRES_PASSWORD: "mrack2319"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: